### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by gongxxuan** [yuteng/nighttime-dehazing#1]
直接运行您的代码这样的错误：

![image](https://user-images.githubusercontent.com/67060808/93853242-18626280-fce6-11ea-9835-2d9886556bc4.png)

**Comment by sunglyoungKim** [comment]
I have the same problem. The source code doesn't have guidefilter funtion

**Comment by shrutiphutke** [comment]
I have the same problem. The source code doesn't have guidefilter funtion

**Comment by yx-chan131** [comment]
Hi, @gongxxuan @sunglyoungKim @shrutiphutke have you solved this problem?

**Comment by shrutiphutke** [comment]
> Hi, @gongxxuan @sunglyoungKim @shrutiphutke have you solved this problem?

No..
